[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>", "John Nunley <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1"
async-rustls = { path = "../.." }
rustls-pemfile = "1"
rustls-webpki = "0.101"
smol = "1"
webpki-roots = "0.23"
